BUNDLES = [
    '//apps/metron/gui:onos-apps-metron-gui',
    '//apps/metron/mgr/api:onos-apps-metron-mgr-api',
    '//apps/metron/mgr/app:onos-apps-metron-mgr-app',
    '//apps/metron/web:onos-apps-metron-web',
]

REQUIRED_APPS = [
    'org.onosproject.drivers.server',
]

onos_app(
    title = 'Metron NFV Controller',
    category = 'Traffic Engineering',
    origin = 'KTH Royal Institute of Technology &amp; RISE &amp; UBITECH',
    url = 'https://github.com/gkatsikas/onos/tree/metron-ctrl-1.14.0',
    description = 'Metron realizes NFV service chains at the true speed of the underlying hardware',
    included_bundles = BUNDLES,
    required_apps = REQUIRED_APPS,
)
